import Link from 'next/link';
import { industries, projects, services, site } from '@/lib/data';
import FAQList from '@/components/FAQList';
import ContactForm from '@/components/ContactForm';

const whyUs = [
  { title: 'Expert Solar Consultation', text: 'Load analysis and practical guidance before you invest.', icon: '/images/icons/solar-consultation.png' },
  { title: 'Reliable Installation', text: 'Clean execution and commissioning done by experienced field teams.', icon: '/images/icons/solar-installation-service.png' },
  { title: 'Quality-Tested Systems', text: 'Durable components selected for long-term performance and service.', icon: '/images/icons/quality-tested-systems.png' },
  { title: 'After-Sales Support', text: 'AMC, service response and technical follow-up after handover.', icon: '/images/icons/after-sales.png' },
];

const clients = [
  { name: 'JSS Mahavidyapeetha', src: '/images/clients/jss-mahavidyapeetha-mysore.png' },
  { name: 'BVV Sangha Bagalkote', src: '/images/clients/bvv-sangha-bagalkote.png' },
  { name: 'Emmvee Solar', src: '/images/clients/emmvee-solar-bengaluru.png' },
  { name: 'Dayananda Sagar University', src: '/images/clients/dayananda-sagar-university-harohalli.png' },
  { name: 'Saurdarshan Solar', src: '/images/clients/saurdharshan-solar.png' },
];

export default function Home(){return <main>
<section className="hero"><div className="container"><div className="hero-grid"><div className="hero-copy"><span className="eyebrow">Solar · Water · Pumping · EPC</span><h1>Engineering that has to work.</h1><p>Sunspectrum Enterprises designs and executes solar energy systems, water treatment plants, pumping systems, electrical works and turnkey EPC projects for residential, commercial and institutional clients across Karnataka.</p><div className="hero-actions"><Link className="button button-white" href="#contact">Request a quotation <span>↗</span></Link><Link className="button button-outline" href="#projects">View selected work</Link></div></div><div className="hero-image"><div className="hero-frame"><img src="/images/products/solar-panels/rooftop-solar-panel.webp" alt="Rooftop solar installation" /></div></div></div><div className="hero-meta"><div className="hero-stat"><strong>120+</strong><span>Projects delivered</span></div><div className="hero-stat"><strong>14+ years</strong><span>Field experience</span></div><div className="hero-stat"><strong>60+</strong><span>Clients</span></div><div className="hero-stat"><strong>8 MW+</strong><span>Solar capacity installed</span></div></div></div></section>
<section className="section" id="services"><div className="container"><div className="section-head"><span className="eyebrow">01 / Services</span><div><h2>One team for connected utility systems.</h2><p>From site assessment and design through installation, commissioning and service, the scope stays clear.</p></div></div><div className="service-list">{services.map(s=><div className="service-row" key={s.code}><span className="num">{s.code}</span><h3>{s.title}</h3><p>{s.text}</p><Link className="text-link" href={s.href}>Details ↗</Link></div>)}</div></div></section>
<section className="section why-us" id="why-us"><div className="container"><div className="section-head"><span className="eyebrow">02 / Why us</span><div><h2>Clear advice, dependable execution and service that continues after install.</h2><p>We make technical decisions practical, site-aware and built around performance over the long term.</p></div></div><div className="why-us-grid">{whyUs.map(item=><div className="why-card" key={item.title}><img src={item.icon} alt={item.title} /><h3>{item.title}</h3><p>{item.text}</p></div>)}</div></div></section>
<section className="section" id="projects"><div className="container"><div className="section-head"><span className="eyebrow">03 / Selected work</span><div><h2>Projects presented as engineering briefs, not brochure tiles.</h2><p>A selection of project scopes from solar, water, pumping and hospitality applications.</p></div></div><div className="project-list">{projects.map((p,i)=><article className="project" key={p.title}><div className="project-media"><img src={p.image} alt={p.title}/></div><div className="project-copy"><span className="project-index">PROJECT {String(i+1).padStart(2,'0')}</span><h3>{p.title}</h3><div className="project-meta"><span>{p.client}</span><span>{p.location}</span></div><div className="project-specs"><div><strong>Problem</strong><span>{p.problem}</span></div><div><strong>Solution</strong><span>{p.solution}</span></div><div><strong>Technologies</strong><span>{p.tech}</span></div><div><strong>Measure</strong><span>{p.measure}</span></div></div><p className="project-result"><strong>Result — </strong>{p.result}</p></div></article>)}</div></div></section>
<section className="section clients-section" id="clients"><div className="container"><div className="section-head"><span className="eyebrow">04 / Our clients</span><div><h2>Trusted by institutions, commercial operators and growing businesses.</h2><p>We work across campuses, industrial sites, hospitality, utilities and agriculture.</p></div></div><div className="clients-grid">{clients.map(client=><div className="client-badge" key={client.name}><img src={client.src} alt={client.name} /><span>{client.name}</span></div>)}</div></div></section>
<section className="section" id="industries"><div className="container"><div className="section-head"><span className="eyebrow">05 / Industries</span><div><h2>Built for sites where reliability matters.</h2><p>Systems are planned around actual load, site conditions, operating patterns and service requirements.</p></div></div><div className="industry-grid">{industries.map(([name,text])=><div className="industry" key={name}><strong>{name}</strong><p>{text}</p></div>)}</div></div></section>
<section className="section process"><div className="container"><div className="section-head"><span className="eyebrow">06 / Delivery</span><div><h2>A clear route from first site visit to handover.</h2><p>Each stage has a practical output, keeping decisions and responsibilities visible.</p></div></div><div className="process-list">{[['01','Consultation','Understand load, site constraints and project goal.'],['02','Design','Develop the appropriate technical scope and system.'],['03','Procurement','Coordinate equipment, materials and project logistics.'],['04','Execution','Install, test, commission and document the system.'],['05','Support','Service, AMC and maintenance planning after handover.']].map(([n,t,d])=><div className="process-step" key={n}><span>{n}</span><h3>{t}</h3><p>{d}</p></div>)}</div></div></section>
<section className="section" id="faq"><div className="container"><div className="faq-layout"><div className="faq-intro"><span className="eyebrow">07 / FAQ</span><h2>Questions buyers usually ask.</h2></div><FAQList/></div></div></section>
<section className="section contact" id="contact"><div className="container"><div className="section-head"><span className="eyebrow">08 / Contact</span><div><h2>Tell us what the site needs.</h2><p>Share the location, capacity, service requirement and timeline. The quickest route is WhatsApp.</p></div></div><div className="contact-grid"><div><ContactForm/></div><div className="contact-details"><div className="contact-detail"><span>Office</span><p>{site.address}</p></div><div className="contact-detail"><span>Phone</span><a href={site.phoneHref}>{site.phone}</a></div><div className="contact-detail"><span>Email</span><a href={`mailto:${site.email}`}>{site.email}</a></div><div className="contact-detail"><span>Working hours</span><p>{site.hours}</p></div><div className="map"><iframe title="Sunspectrum Enterprises location" src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d276.4178551139093!2d76.60791602816482!3d12.248248925105111!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x3baf65eddcb357d5%3A0xb01d9f240e853395!2sSunspectrum%20Enterprises!5e0!3m2!1sen!2sin!4v1772096087840!5m2!1sen!2sin" loading="lazy"/></div></div></div></div></section>
</main>}
